# Molly Moran
## Week 12 11/13/2025
### Python - Pandas DataFrame Processing

In [2]:
# import
import numpy as np
from numpy.random import *
import pandas as pd
from pandas import *

In [6]:
# drop entries
df = DataFrame(np.arange(16).reshape(4,4),
              index=['Ohio','Colorado','Utah','New York'],
              columns =['one','two','three','four'])
df

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [7]:
df.T

       Ohio  Colorado  Utah  New York
one       0         4     8        12
two       1         5     9        13
three     2         6    10        14
four      3         7    11        15

In [8]:
df

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [9]:
dfc =df.copy()

In [10]:
dfc

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [11]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
df.index

Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='object')

In [13]:
df.columns

Index(['one', 'two', 'three', 'four'], dtype='object')

In [14]:
# delete row
df.drop(['Colorado'])

          one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

In [15]:
df.drop(['Ohio'])

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [16]:
df

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [20]:
df.drop(['Ohio'], inplace=True)

KeyError: "['Ohio'] not found in axis"

In [21]:
df3 = df
df3

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [24]:
df

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [25]:
df3

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [26]:
dfc

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
df.drop(['Colorado','Utah'], inplace=True)

In [30]:
df

          one  two  three  four
New York   12   13     14    15

In [31]:
df3

          one  two  three  four
New York   12   13     14    15

In [32]:
df = dfc.copy()
df

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [34]:
# drop column
df.drop(['three'], axis=1)

          one  two  four
Ohio        0    1     3
Colorado    4    5     7
Utah        8    9    11
New York   12   13    15

In [36]:
df.drop(['three','one'], axis='columns')

          two  four
Ohio        1     3
Colorado    5     7
Utah        9    11
New York   13    15

In [37]:
df

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [38]:
df.drop(['three','one'], axis='columns', inplace=True)

In [39]:
df

          two  four
Ohio        1     3
Colorado    5     7
Utah        9    11
New York   13    15

In [40]:
df = dfc.copy()
df

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [42]:
df['one']

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int32

In [43]:
df[['one','four']]

          one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

In [45]:
df[df['three'] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [46]:
df> 5

            one    two  three   four
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [47]:
df[df<5] = 0
df

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [48]:
df.loc['Ohio']

one      0
two      0
three    0
four     0
Name: Ohio, dtype: int32

In [49]:
df.loc[['Ohio', 'New York']]

          one  two  three  four
Ohio        0    0      0     0
New York   12   13     14    15

In [52]:
df.loc['Colorado',['three','two']]

three    6
two      5
Name: Colorado, dtype: int32

In [54]:
# iloc for index
df.iloc[0]

one      0
two      0
three    0
four     0
Name: Ohio, dtype: int32

In [56]:
df.iloc[[0,1]]

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7

In [57]:
df.iloc[[0,2],[2,3]]

      three  four
Ohio      0     0
Utah     10    11

In [60]:
df = DataFrame(np.arange(16).reshape(4,4))
df

    0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [61]:
df.loc[[1,3]]

    0   1   2   3
1   4   5   6   7
3  12  13  14  15

In [63]:
# Arithmitic and alignmnet of data
df1 = DataFrame(np.arange(9).reshape(3,3),columns=list('bcd'), index=['Ohio','Texas','Colorado'])
df2 = DataFrame(np.arange(12).reshape(4,3),columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [64]:
df1

          b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [65]:
df2

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [66]:
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [69]:
df1.add(df2,fill_value=0) # fill the non + number with 0 + number

            b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [71]:
df2

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [70]:
df1

          b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [72]:
df1['e']=df1['b']+df1['d']
df1

          b  c  d   e
Ohio      0  1  2   2
Texas     3  4  5   8
Colorado  6  7  8  14

In [73]:
# Sort and Rank
df=DataFrame(np.arange(8).reshape(2,4)*10, columns=list('dabc'), index=['three','one'])
df

        d   a   b   c
three   0  10  20  30
one    40  50  60  70

In [74]:
#sort index rows by labels
df.sort_index()

        d   a   b   c
one    40  50  60  70
three   0  10  20  30

In [75]:
# sort index by columns
df.sort_index(axis=1)

        a   b   c   d
three  10  20  30   0
one    50  60  70  40

In [76]:
df

        d   a   b   c
three   0  10  20  30
one    40  50  60  70

In [77]:
df.sort_index(axis=1,ascending=False)

        d   c   b   a
three   0  30  20  10
one    40  70  60  50

In [78]:
df

        d   a   b   c
three   0  10  20  30
one    40  50  60  70

In [79]:
df.sort_index(axis=1,inplace=True)

In [80]:
df

        a   b   c   d
three  10  20  30   0
one    50  60  70  40

In [98]:
# sort by value
df = DataFrame({'b:'[4,7,-3,-2],'a':[0,-1,3,2], index=['one','three','four','two'})
df

SyntaxError: invalid syntax (<ipython-input-98-d799bdf81ed9>, line 2)

In [99]:
df.sort_values(by=['b','a'])

        a   b   c   d
three  10  20  30   0
one    50  60  70  40

In [88]:
df.sort_values(by='one',axis=1)

        d   a   b   c
three   0  10  20  30
one    40  50  60  70

In [91]:
df.sort_values(by='four',axis=1)

KeyError: 'four'

In [92]:
df.sort_values(by=['one','four'],axis=1)

KeyError: 'four'

In [96]:
df.sort_values(by=['one','four'],axis=1, inplace=True)

KeyError: 'four'

In [100]:
df = DataFrame(random(6).reshape(2,3)*50)
df.index.name = 'index'
df

               0          1          2
index
0      10.395997  28.371497  14.515696
1      11.586394   2.258979  21.939661

In [101]:
df.columns.name = 'Columns'
df

Columns          0          1          2
index
0        10.395997  28.371497  14.515696
1        11.586394   2.258979  21.939661