# Molly Moran
## Week 12 11/11/2025 - 11/13/2025
### Python - Pandas Series and DataFrame

## What is Pandas?
- Pandas is an open source Python library used for working with data sets.
- It has functions for analyzing, cleaning, exploring, and manipulating data.
- The name "Pandas" has a refrene to both "Panel Data", and **Python Data Analysis**
- The source code for Pandas is located at this GitHub
- Pandas allows us to analyize big data with default and costomized indexing.
- Fast and efficent Series and DataFrame object with default and costomized indexing
- High-Preformance merging and joining of data

In [1]:
# import modules 
import numpy as np
from numpy.random import randn, random
import pandas as pd
from pandas import Series, DataFrame

In [35]:
s = Series(np.arange(5,21))
s

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
15    20
dtype: int32

In [36]:
type(s)

pandas.core.series.Series

In [37]:
s.values

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
s.index

RangeIndex(start=0, stop=16, step=1)

In [39]:
# labels
s[0]

5

In [40]:
s[15
 ]

20

In [41]:
s[:5]

0    5
1    6
2    7
3    8
4    9
dtype: int32

In [42]:
s = Series(np.arange(10,41,10), index = ["w","x","y","z"])
s

w    10
x    20
y    30
z    40
dtype: int32

In [43]:
s['w']

10

In [44]:
s['z']

40

In [45]:
s = Series(np.array(['a','b','c','d']), index = [ 100,102,103,105])
s

100    a
102    b
103    c
105    d
dtype: object

In [46]:
s[100]

'a'

In [48]:
summer_olympic = Series([2520, 1122, 937, 847, 713], index = ['USA', 'Russia', 'Germany', 'UK', 'France'])
summer_olympic

USA        2520
Russia     1122
Germany     937
UK          847
France      713
dtype: int64

In [59]:
len(s)

4

In [50]:
summer_olympic['UK']

847

In [51]:
summer_olympic[['USA','UK']]

USA    2520
UK      847
dtype: int64

In [58]:
summer_olypmic[summer_olympic > 800]

NameError: name 'summer_olypmic' is not defined

In [55]:
# convert Series to dictionary
d = summer_olympic.to.dict()
d

AttributeError: 'Series' object has no attribute 'to'

In [54]:
#convert dictionary to series
s = Series(d)
s

NameError: name 'd' is not defined

In [56]:
countries = ['Russia', 'France', 'Spain', 'Germany', 'USA', 'UK', 'Italy']

In [57]:
s2 = Series(d, index = counrties)
s2

NameError: name 'd' is not defined

In [2]:
---------------------------------------

SyntaxError: invalid syntax (<ipython-input-2-1778a6c9b8fc>, line 1)

In [3]:
# Nested Dictonary

d = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio':{2000: 1.5, 2001: 1.7, 2002: 3.6}}
d

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [5]:
df = DataFrame(d)
df

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [6]:
df.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [7]:
df.index

Int64Index([2001, 2002, 2000], dtype='int64')

In [8]:
df.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [9]:
df

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [10]:
df2 = DataFrame(df, index=[2001,2002,2003])
df2

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [11]:
df['Nevada']

2001    2.4
2002    2.9
2000    NaN
Name: Nevada, dtype: float64

In [12]:
df['Nevada'][:2]

2001    2.4
2002    2.9
Name: Nevada, dtype: float64

In [13]:
df['Nevada'][:-1]

2001    2.4
2002    2.9
Name: Nevada, dtype: float64

In [14]:
df['Nevada'][-2:-1]

2002    2.9
Name: Nevada, dtype: float64

In [15]:
df.index.name='year';df.columns.name='State'
df

State  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5