# Molly Moran
## Week 13 11/18/2025 - 11/20/2025
### Python - Pandas DataFrame Processing

In [1]:
# import
import numpy as np
from numpy.random import *
import pandas as pd
from pandas import *

In [2]:
#Data Ranking
df = DataFrame({'a': np.random.choice(np.arange(10,16),size=8), 'b': np.random.choice(np.arange(10,16),size=8)})
df

    a   b
0  14  10
1  11  10
2  15  14
3  14  10
4  10  14
5  11  13
6  12  10
7  15  14

In [3]:
df.rank()

     a    b
0  5.5  2.5
1  2.5  2.5
2  7.5  7.0
3  5.5  2.5
4  1.0  7.0
5  2.5  5.0
6  4.0  2.5
7  7.5  7.0

In [4]:
df.rank().astype(int)

   a  b
0  5  2
1  2  2
2  7  7
3  5  2
4  1  7
5  2  5
6  4  2
7  7  7

In [5]:
# Summerizing data -Statistics
sample = [0.5,0.75,-1.5,-0.85,2.5,-2.8,np.nan,1.8,0.25,3.5,-1.75]

df = DataFrame([ np.random.choice(sample, size=4), np.random.choice(sample, size=4), np.random.choice(sample, size=4), np.random.choice(sample, size=4)], index=list('abcd'), columns= ['one','two','three','four'])
df

    one   two  three  four
a -0.85   NaN  -1.75   1.8
b -0.85 -1.50    NaN   NaN
c -1.75  0.25   2.50   0.5
d  1.80  2.50  -0.85   0.5

In [6]:
df.sum

<bound method DataFrame.sum of     one   two  three  four
a -0.85   NaN  -1.75   1.8
b -0.85 -1.50    NaN   NaN
c -1.75  0.25   2.50   0.5
d  1.80  2.50  -0.85   0.5>

In [7]:
df.sum(axis=1)

a   -0.80
b   -2.35
c    1.50
d    3.95
dtype: float64

In [8]:
df.sum(axis='columns')

a   -0.80
b   -2.35
c    1.50
d    3.95
dtype: float64

In [9]:
df.mean()

one     -0.412500
two      0.416667
three   -0.033333
four     0.933333
dtype: float64

In [10]:
df.mean(axis=1)

a   -0.266667
b   -1.175000
c    0.375000
d    0.987500
dtype: float64

In [11]:
df.mean(axis=1, skipna=False)

a       NaN
b       NaN
c    0.3750
d    0.9875
dtype: float64

In [12]:
# idmax() and idxmin()
# returms the index of the first occurance of the maximim or minimum over the requested axis.

df

    one   two  three  four
a -0.85   NaN  -1.75   1.8
b -0.85 -1.50    NaN   NaN
c -1.75  0.25   2.50   0.5
d  1.80  2.50  -0.85   0.5

In [13]:
df.idxmax()

one      d
two      d
three    c
four     a
dtype: object

In [14]:
df.idxmin()

one      c
two      b
three    a
four     c
dtype: object

In [15]:
df.max()

one      1.8
two      2.5
three    2.5
four     1.8
dtype: float64

In [16]:
df.min()

one     -1.75
two     -1.50
three   -1.75
four     0.50
dtype: float64

In [17]:
df.describe()

            one       two     three      four
count  4.000000  3.000000  3.000000  3.000000
mean  -0.412500  0.416667 -0.033333  0.933333
std    1.534805  2.005202  2.239606  0.750555
min   -1.750000 -1.500000 -1.750000  0.500000
25%   -1.075000 -0.625000 -1.300000  0.500000
50%   -0.850000  0.250000 -0.850000  0.500000
75%   -0.187500  1.375000  0.825000  1.150000
max    1.800000  2.500000  2.500000  1.800000

In [18]:
df.idxmax(axis=1)

a     four
b      one
c    three
d      two
dtype: object

In [19]:
df.idxmin(axis=1)

a    three
b      two
c      one
d    three
dtype: object

In [20]:
data= DataFrame({ 'Date' : ['2023-01-01','2023-01-02','2023-01-03','2023-01-04'],
                 'META': [150,155,148,160],
                 'TSLA' : [200,210,195,220],
                 'GOOGL' : [100,105,95,110]
    
    
    
})

data

         Date  META  TSLA  GOOGL
0  2023-01-01   150   200    100
1  2023-01-02   155   210    105
2  2023-01-03   148   195     95
3  2023-01-04   160   220    110

In [21]:
data.set_index('Date', inplace=True)

In [22]:
data

            META  TSLA  GOOGL
Date
2023-01-01   150   200    100
2023-01-02   155   210    105
2023-01-03   148   195     95
2023-01-04   160   220    110

In [23]:
# find the date with the highest closing price for each stock
data.idxmax()

META     2023-01-04
TSLA     2023-01-04
GOOGL    2023-01-04
dtype: object

In [24]:
data.idxmin()

META     2023-01-03
TSLA     2023-01-03
GOOGL    2023-01-03
dtype: object

In [25]:
data.idxmax(axis=1)

Date
2023-01-01    TSLA
2023-01-02    TSLA
2023-01-03    TSLA
2023-01-04    TSLA
dtype: object

In [26]:
data_t = data.T
data_t

Date   2023-01-01  2023-01-02  2023-01-03  2023-01-04
META          150         155         148         160
TSLA          200         210         195         220
GOOGL         100         105          95         110

In [27]:
# Find the stokcs with the minimum and maximum values for a specific date: "2023-01-02"
data_t.idxmax()

Date
2023-01-01    TSLA
2023-01-02    TSLA
2023-01-03    TSLA
2023-01-04    TSLA
dtype: object

In [28]:
data_t['2023-01-02'].idxmax()

'TSLA'

In [29]:
data_t['2023-01-02'].idxmin()

'GOOGL'

In [30]:
# Missing Data - np.nan
sample = [1,2,3,4,5,6,np.nan]

df = DataFrame([np.random.choice(sample,size=5),np.random.choice(sample,size=5),np.random.choice(sample,size=5),np.random.choice(sample,size=5),])
df

     0    1    2    3    4
0  1.0  6.0  6.0  3.0  1.0
1  NaN  3.0  1.0  5.0  1.0
2  6.0  3.0  5.0  6.0  NaN
3  4.0  1.0  6.0  2.0  6.0

In [31]:
df.dropna()

     0    1    2    3    4
0  1.0  6.0  6.0  3.0  1.0
3  4.0  1.0  6.0  2.0  6.0

In [32]:
df.dropna(how='any')

     0    1    2    3    4
0  1.0  6.0  6.0  3.0  1.0
3  4.0  1.0  6.0  2.0  6.0

In [33]:
df.dropna(how='all')

     0    1    2    3    4
0  1.0  6.0  6.0  3.0  1.0
1  NaN  3.0  1.0  5.0  1.0
2  6.0  3.0  5.0  6.0  NaN
3  4.0  1.0  6.0  2.0  6.0

In [34]:
df.dropna(axis=1)

     1    2    3
0  6.0  6.0  3.0
1  3.0  1.0  5.0
2  3.0  5.0  6.0
3  1.0  6.0  2.0

In [35]:
df.dropna(thresh=2)#keep only the reows having 2 or more valid data

     0    1    2    3    4
0  1.0  6.0  6.0  3.0  1.0
1  NaN  3.0  1.0  5.0  1.0
2  6.0  3.0  5.0  6.0  NaN
3  4.0  1.0  6.0  2.0  6.0

In [36]:
df.dropna(thresh=4)

     0    1    2    3    4
0  1.0  6.0  6.0  3.0  1.0
1  NaN  3.0  1.0  5.0  1.0
2  6.0  3.0  5.0  6.0  NaN
3  4.0  1.0  6.0  2.0  6.0

In [37]:
df.fillna(0)

     0    1    2    3    4
0  1.0  6.0  6.0  3.0  1.0
1  0.0  3.0  1.0  5.0  1.0
2  6.0  3.0  5.0  6.0  0.0
3  4.0  1.0  6.0  2.0  6.0

In [38]:
df.fillna(1)

     0    1    2    3    4
0  1.0  6.0  6.0  3.0  1.0
1  1.0  3.0  1.0  5.0  1.0
2  6.0  3.0  5.0  6.0  1.0
3  4.0  1.0  6.0  2.0  6.0

In [39]:
df

     0    1    2    3    4
0  1.0  6.0  6.0  3.0  1.0
1  NaN  3.0  1.0  5.0  1.0
2  6.0  3.0  5.0  6.0  NaN
3  4.0  1.0  6.0  2.0  6.0

In [40]:
df.fillna(0, inplace=True)

In [41]:
df

     0    1    2    3    4
0  1.0  6.0  6.0  3.0  1.0
1  0.0  3.0  1.0  5.0  1.0
2  6.0  3.0  5.0  6.0  0.0
3  4.0  1.0  6.0  2.0  6.0

In [42]:
#Sample DataFrame with NaN values 
df = DataFrame({'A': np.random.choice(sample,size=10),
                'B': np.random.choice(sample,size=10)
    
    
})
df

     A    B
0  1.0  3.0
1  3.0  2.0
2  NaN  6.0
3  3.0  3.0
4  2.0  3.0
5  NaN  1.0
6  6.0  3.0
7  2.0  6.0
8  6.0  2.0
9  2.0  NaN

In [43]:
df.fillna(0)

     A    B
0  1.0  3.0
1  3.0  2.0
2  0.0  6.0
3  3.0  3.0
4  2.0  3.0
5  0.0  1.0
6  6.0  3.0
7  2.0  6.0
8  6.0  2.0
9  2.0  0.0

In [44]:
df

     A    B
0  1.0  3.0
1  3.0  2.0
2  NaN  6.0
3  3.0  3.0
4  2.0  3.0
5  NaN  1.0
6  6.0  3.0
7  2.0  6.0
8  6.0  2.0
9  2.0  NaN

In [45]:
# Fill NaN values with the previous non-null value
df.fillna(method='ffill')

     A    B
0  1.0  3.0
1  3.0  2.0
2  3.0  6.0
3  3.0  3.0
4  2.0  3.0
5  2.0  1.0
6  6.0  3.0
7  2.0  6.0
8  6.0  2.0
9  2.0  2.0

In [46]:
df['A'].fillna(value=df['A'].mean())

0    1.000
1    3.000
2    3.125
3    3.000
4    2.000
5    3.125
6    6.000
7    2.000
8    6.000
9    2.000
Name: A, dtype: float64

In [47]:
# Replace NaNs with the mean of values in the same column
df['A'].fillna(value=df['A'].mean())

0    1.000
1    3.000
2    3.125
3    3.000
4    2.000
5    3.125
6    6.000
7    2.000
8    6.000
9    2.000
Name: A, dtype: float64

In [48]:
df

     A    B
0  1.0  3.0
1  3.0  2.0
2  NaN  6.0
3  3.0  3.0
4  2.0  3.0
5  NaN  1.0
6  6.0  3.0
7  2.0  6.0
8  6.0  2.0
9  2.0  NaN

In [49]:
df.fillna({'A':df['A'].mean(), 'B': df['B'].median()})

       A    B
0  1.000  3.0
1  3.000  2.0
2  3.125  6.0
3  3.000  3.0
4  2.000  3.0
5  3.125  1.0
6  6.000  3.0
7  2.000  6.0
8  6.000  2.0
9  2.000  3.0

In [50]:
df.fillna({'A':df['A'].mean(), 'B': df['B'].median()}, inplace=True)

In [51]:
df

       A    B
0  1.000  3.0
1  3.000  2.0
2  3.125  6.0
3  3.000  3.0
4  2.000  3.0
5  3.125  1.0
6  6.000  3.0
7  2.000  6.0
8  6.000  2.0
9  2.000  3.0

In [52]:
# value counts
df = DataFrame({'Qu1': np.random.choice(np.arange(10,101,10), size=5),
                'Qu2': np.random.choice(np.arange(10,101,10), size=5),
                'Qu3': np.random.choice(np.arange(10,101,10), size=5),
                'Qu14': np.random.choice(np.arange(10,101,10), size=5),
               },
              index= list('abcde'))
df

   Qu1  Qu2  Qu3  Qu14
a   80   60   40    60
b   20   10  100    20
c   90   10   70    80
d   60  100   70   100
e   70   80   10    10

In [53]:
df.values

array([[ 80,  60,  40,  60],
       [ 20,  10, 100,  20],
       [ 90,  10,  70,  80],
       [ 60, 100,  70, 100],
       [ 70,  80,  10,  10]])

In [54]:
df['Qu1'].value_counts()

70    1
20    1
60    1
90    1
80    1
Name: Qu1, dtype: int64

In [55]:
df['Qu2'].value_counts()

10     2
60     1
100    1
80     1
Name: Qu2, dtype: int64

In [56]:
df

   Qu1  Qu2  Qu3  Qu14
a   80   60   40    60
b   20   10  100    20
c   90   10   70    80
d   60  100   70   100
e   70   80   10    10

In [57]:
df.loc['a'].value_counts()

60    2
40    1
80    1
Name: a, dtype: int64

In [58]:
df.loc['e'].value_counts()

10    2
70    1
80    1
Name: e, dtype: int64

In [59]:
df.apply(value_counts)

     Qu1  Qu2  Qu3  Qu14
10   NaN  2.0  1.0   1.0
20   1.0  NaN  NaN   1.0
40   NaN  NaN  1.0   NaN
60   1.0  1.0  NaN   1.0
70   1.0  NaN  2.0   NaN
80   1.0  1.0  NaN   1.0
90   1.0  NaN  NaN   NaN
100  NaN  1.0  1.0   1.0

In [60]:
df.apply(value_counts).fillna(0)

     Qu1  Qu2  Qu3  Qu14
10   0.0  2.0  1.0   1.0
20   1.0  0.0  0.0   1.0
40   0.0  0.0  1.0   0.0
60   1.0  1.0  0.0   1.0
70   1.0  0.0  2.0   0.0
80   1.0  1.0  0.0   1.0
90   1.0  0.0  0.0   0.0
100  0.0  1.0  1.0   1.0

In [61]:
rs = df.apply(value_counts).fillna(0).astype(int)
rs

     Qu1  Qu2  Qu3  Qu14
10     0    2    1     1
20     1    0    0     1
40     0    0    1     0
60     1    1    0     1
70     1    0    2     0
80     1    1    0     1
90     1    0    0     0
100    0    1    1     1

In [62]:
rs.index.name='values'

In [63]:
rs.columns.name='questions'

In [64]:
rs

questions  Qu1  Qu2  Qu3  Qu14
values
10           0    2    1     1
20           1    0    0     1
40           0    0    1     0
60           1    1    0     1
70           1    0    2     0
80           1    1    0     1
90           1    0    0     0
100          0    1    1     1

In [65]:
# a dataset of customer oreders for an online store

sample = ['T-shirt', 'Hoodie', 'Mug']
data = {'Order_ID': np.random.choice(np.arange(500,5001), size=20,
replace=False).astype(int),
        'Product': np.random.choice(sample, size=20),
        'Date': date_range(start='11-20-2025', periods=20)
       }
df = DataFrame(data)
df

    Order_ID  Product       Date
0       3381      Mug 2025-11-20
1       2460   Hoodie 2025-11-21
2       4313   Hoodie 2025-11-22
3       1306      Mug 2025-11-23
4       2152      Mug 2025-11-24
5       4554   Hoodie 2025-11-25
6       2117  T-shirt 2025-11-26
7       2892      Mug 2025-11-27
8       3580  T-shirt 2025-11-28
9       1722   Hoodie 2025-11-29
10      4337   Hoodie 2025-11-30
11      2193      Mug 2025-12-01
12      2962   Hoodie 2025-12-02
13      3888      Mug 2025-12-03
14      1465      Mug 2025-12-04
15      2196      Mug 2025-12-05
16       782      Mug 2025-12-06
17       977      Mug 2025-12-07
18       962   Hoodie 2025-12-08
19      2616  T-shirt 2025-12-09

In [66]:
df.set_index('Date', inplace=True)
df

            Order_ID  Product
Date
2025-11-20      3381      Mug
2025-11-21      2460   Hoodie
2025-11-22      4313   Hoodie
2025-11-23      1306      Mug
2025-11-24      2152      Mug
2025-11-25      4554   Hoodie
2025-11-26      2117  T-shirt
2025-11-27      2892      Mug
2025-11-28      3580  T-shirt
2025-11-29      1722   Hoodie
2025-11-30      4337   Hoodie
2025-12-01      2193      Mug
2025-12-02      2962   Hoodie
2025-12-03      3888      Mug
2025-12-04      1465      Mug
2025-12-05      2196      Mug
2025-12-06       782      Mug
2025-12-07       977      Mug
2025-12-08       962   Hoodie
2025-12-09      2616  T-shirt

In [67]:
df['Product'].value_counts()

Mug        10
Hoodie      7
T-shirt     3
Name: Product, dtype: int64