# Molly Moran
## Week 13 11/20/2025
### Python - Pandas DataFrame, Mapping, Applying and Grouping

In [4]:
# import
import numpy as np
from numpy.random import *
import pandas as pd
from pandas import *

In [8]:
# mapping  - data points

df = DataFrame({'city': ['Alma', 'Brian Head', 'Fox Park', 'Lake Mary'],
               'altitude': [10355, 9800, 9062, 8966]})
df

         city  altitude
0        Alma     10355
1  Brian Head      9800
2    Fox Park      9062
3   Lake Mary      8966

In [9]:
st = {'Alma': 'Colorado', 'Brain Head':'Utah', 'Fox Park':'Wyoming','Lake Mary':'California'}
st

{'Alma': 'Colorado',
 'Brain Head': 'Utah',
 'Fox Park': 'Wyoming',
 'Lake Mary': 'California'}

In [10]:
df['state'] = df['city'].map(st)
df

         city  altitude       state
0        Alma     10355    Colorado
1  Brian Head      9800         NaN
2    Fox Park      9062     Wyoming
3   Lake Mary      8966  California

In [12]:
#apply
dfc = df.copy()
df['altitude'] = df['altitude'].apply(lambda x: x/ 3.2808)
df

         city    altitude       state
0        Alma  962.034376    Colorado
1  Brian Head  910.471935         NaN
2    Fox Park  841.907824     Wyoming
3   Lake Mary  832.988915  California

In [13]:
df['altitude'] = df['altitude'].apply(lambda x: np.nan if x < 2808 else x)
df

         city  altitude       state
0        Alma       NaN    Colorado
1  Brian Head       NaN         NaN
2    Fox Park       NaN     Wyoming
3   Lake Mary       NaN  California

In [14]:
df = DataFrame(randn(4,3), columns=list('bde'), index=['UT', 'OH', 'TX', 'OR'])
df

           b         d         e
UT  0.605242 -1.448794  0.514466
OH -1.091491 -1.925052  0.539380
TX  1.497080  1.779128  0.117263
OR -0.636928  0.664438  1.265487

In [15]:
df.apply(lambda x:x.max() - x.min())

b    2.588571
d    3.704181
e    1.148224
dtype: float64

In [16]:
df.apply(lambda x:x.max() - x.min(), axis=1)

UT    2.054036
OH    2.464432
TX    1.661866
OR    1.902415
dtype: float64

In [17]:
df.apply(value_counts)

             b    d    e
-1.925052  NaN  1.0  NaN
-1.448794  NaN  1.0  NaN
-1.091491  1.0  NaN  NaN
-0.636928  1.0  NaN  NaN
 0.117263  NaN  NaN  1.0
 0.514466  NaN  NaN  1.0
 0.539380  NaN  NaN  1.0
 0.605242  1.0  NaN  NaN
 0.664438  NaN  1.0  NaN
 1.265487  NaN  NaN  1.0
 1.497080  1.0  NaN  NaN
 1.779128  NaN  1.0  NaN

In [20]:
# groupby is the most frequently used function in data analysis.
# It is used for grouping the data points (i.e. rows) based on the distinct values

cars = ['Toyota','Ford','GMC','Dodge']
df = DataFrame({'brand': np.random.choice(cars, size=20),
               'price': np.random.randint(40000,85000, size=20)
                
               })
df

     brand  price
0     Ford  77768
1    Dodge  54410
2     Ford  81057
3   Toyota  55684
4     Ford  68124
5    Dodge  40380
6     Ford  81808
7   Toyota  83123
8   Toyota  70278
9      GMC  45867
10    Ford  50898
11   Dodge  75995
12  Toyota  81074
13   Dodge  68654
14    Ford  58243
15    Ford  43495
16  Toyota  51433
17   Dodge  72274
18    Ford  49834
19     GMC  80043

In [21]:
df['brand'].value_counts()

Ford      8
Dodge     5
Toyota    5
GMC       2
Name: brand, dtype: int64

In [22]:
df.groupby('brand').count()

        price
brand
Dodge       5
Ford        8
GMC         2
Toyota      5

In [23]:
df.groupby('brand').sum()

         price
brand
Dodge   311713
Ford    511227
GMC     125910
Toyota  341592

In [25]:
rs = df.groupby('brand').mean()
rs

            price
brand
Dodge   62342.600
Ford    63903.375
GMC     62955.000
Toyota  68318.400

In [26]:
df

     brand  price
0     Ford  77768
1    Dodge  54410
2     Ford  81057
3   Toyota  55684
4     Ford  68124
5    Dodge  40380
6     Ford  81808
7   Toyota  83123
8   Toyota  70278
9      GMC  45867
10    Ford  50898
11   Dodge  75995
12  Toyota  81074
13   Dodge  68654
14    Ford  58243
15    Ford  43495
16  Toyota  51433
17   Dodge  72274
18    Ford  49834
19     GMC  80043

In [27]:
rs = df.groupby('brand')['price'].mean()
rs

brand
Dodge     62342.600
Ford      63903.375
GMC       62955.000
Toyota    68318.400
Name: price, dtype: float64

In [28]:
rs = df.groupby('brand')[['price']].mean() # double brackets is a data frame
rs

            price
brand
Dodge   62342.600
Ford    63903.375
GMC     62955.000
Toyota  68318.400

In [29]:
df

     brand  price
0     Ford  77768
1    Dodge  54410
2     Ford  81057
3   Toyota  55684
4     Ford  68124
5    Dodge  40380
6     Ford  81808
7   Toyota  83123
8   Toyota  70278
9      GMC  45867
10    Ford  50898
11   Dodge  75995
12  Toyota  81074
13   Dodge  68654
14    Ford  58243
15    Ford  43495
16  Toyota  51433
17   Dodge  72274
18    Ford  49834
19     GMC  80043

In [31]:
df.sort_values(by='brand', inplace=True)

In [32]:
df

     brand  price
1    Dodge  54410
17   Dodge  72274
5    Dodge  40380
11   Dodge  75995
13   Dodge  68654
0     Ford  77768
2     Ford  81057
4     Ford  68124
6     Ford  81808
15    Ford  43495
14    Ford  58243
18    Ford  49834
10    Ford  50898
9      GMC  45867
19     GMC  80043
8   Toyota  70278
7   Toyota  83123
16  Toyota  51433
3   Toyota  55684
12  Toyota  81074

In [33]:
df['cum_sum'] = df.groupby('brand').cumsum()
df

     brand  price  cum_sum
1    Dodge  54410    54410
17   Dodge  72274   126684
5    Dodge  40380   167064
11   Dodge  75995   243059
13   Dodge  68654   311713
0     Ford  77768    77768
2     Ford  81057   158825
4     Ford  68124   226949
6     Ford  81808   308757
15    Ford  43495   352252
14    Ford  58243   410495
18    Ford  49834   460329
10    Ford  50898   511227
9      GMC  45867    45867
19     GMC  80043   125910
8   Toyota  70278    70278
7   Toyota  83123   153401
16  Toyota  51433   204834
3   Toyota  55684   260518
12  Toyota  81074   341592

In [45]:
# groupby using two columns
sample1 = list('abcd')
sample2 = ['one','two','three','four']

df = DataFrame({
    'k1': np.random.choice(sample1,size=20),
    'k2':np.random.choice(sample2,size=20),
    'dataset1': np.random.randn(20),
    'dataset2': np.random.randn(20),
    'dataset3': np.random.randn(20),
    
})

df

   k1     k2  dataset1  dataset2  dataset3
0   b    two -0.792450  2.017948  0.330035
1   b  three  2.141436  0.129492  0.014721
2   a    one -1.599737 -1.629112 -0.104425
3   a   four  0.771253  2.071970 -1.201849
4   b    one  1.330810  0.432773 -0.741889
5   d   four  0.188952  0.790813  0.068548
6   c    two -0.448175 -1.990082  0.307570
7   a    one  0.824213 -1.409855  0.799387
8   c    one  0.723800  0.036446 -0.001945
9   d    one  0.221492 -1.440374  0.852273
10  c    two  0.726365 -1.942570  0.905642
11  b    two -0.400200  1.530986  1.897941
12  c    two  0.705668 -0.923271 -3.125748
13  c  three -1.030652  0.331315  1.005287
14  b    two  1.303626 -0.072866  0.138477
15  d    two  1.065741 -2.294353 -0.322438
16  b  three -0.841513  0.505073 -1.113250
17  b  three  0.514776  1.299271 -0.361770
18  b   four  0.500976  1.678671  0.324814
19  a  three  0.420597 -2.168598 -0.483366

In [46]:
df.groupby('k1').count()

    k2  dataset1  dataset2  dataset3
k1
a    4         4         4         4
b    8         8         8         8
c    5         5         5         5
d    3         3         3         3

In [47]:
df.groupby('k1').sum()

    dataset1  dataset2  dataset3
k1
a   0.416325 -3.135594 -0.990253
b   3.757462  7.521350  0.489079
c   0.677006 -4.488163 -0.909194
d   1.476185 -2.943914  0.598383

In [48]:
df.groupby(['k1', 'k2']).sum()

          dataset1  dataset2  dataset3
k1 k2
a  four   0.771253  2.071970 -1.201849
   one   -0.775524 -3.038967  0.694961
   three  0.420597 -2.168598 -0.483366
b  four   0.500976  1.678671  0.324814
   one    1.330810  0.432773 -0.741889
   three  1.814699  1.933837 -1.460299
   two    0.110977  3.476069  2.366453
c  one    0.723800  0.036446 -0.001945
   three -1.030652  0.331315  1.005287
   two    0.983858 -4.855923 -1.912535
d  four   0.188952  0.790813  0.068548
   one    0.221492 -1.440374  0.852273
   two    1.065741 -2.294353 -0.322438

In [49]:
df.groupby(['k1', 'k2']).count()

          dataset1  dataset2  dataset3
k1 k2
a  four          1         1         1
   one           2         2         2
   three         1         1         1
b  four          1         1         1
   one           1         1         1
   three         3         3         3
   two           3         3         3
c  one           1         1         1
   three         1         1         1
   two           3         3         3
d  four          1         1         1
   one           1         1         1
   two           1         1         1

In [50]:
df.groupby(['k1', 'k2']).mean

()

()

In [51]:
df.groupby(['k1', 'k2'])[['dataset1']].sum()

          dataset1
k1 k2
a  four   0.771253
   one   -0.775524
   three  0.420597
b  four   0.500976
   one    1.330810
   three  1.814699
   two    0.110977
c  one    0.723800
   three -1.030652
   two    0.983858
d  four   0.188952
   one    0.221492
   two    1.065741

In [52]:
df.groupby(['k1', 'k2'])[['dataset1','dataset3']].sum()

          dataset1  dataset3
k1 k2
a  four   0.771253 -1.201849
   one   -0.775524  0.694961
   three  0.420597 -0.483366
b  four   0.500976  0.324814
   one    1.330810 -0.741889
   three  1.814699 -1.460299
   two    0.110977  2.366453
c  one    0.723800 -0.001945
   three -1.030652  1.005287
   two    0.983858 -1.912535
d  four   0.188952  0.068548
   one    0.221492  0.852273
   two    1.065741 -0.322438

In [54]:
df['dataset1'].groupby(df['k1']).mean()

k1
a    0.104081
b    0.469683
c    0.135401
d    0.492062
Name: dataset1, dtype: float64

In [55]:
group = df.groupby(['k1','k2'])[['dataset3']]
group

In [57]:
group.sum()

          dataset3
k1 k2
a  four  -1.201849
   one    0.694961
   three -0.483366
b  four   0.324814
   one   -0.741889
   three -1.460299
   two    2.366453
c  one   -0.001945
   three  1.005287
   two   -1.912535
d  four   0.068548
   one    0.852273
   two   -0.322438

In [59]:
group.mean()

          dataset3
k1 k2
a  four  -1.201849
   one    0.347481
   three -0.483366
b  four   0.324814
   one   -0.741889
   three -0.486766
   two    0.788818
c  one   -0.001945
   three  1.005287
   two   -0.637512
d  four   0.068548
   one    0.852273
   two   -0.322438

In [61]:
group.count()

          dataset3
k1 k2
a  four          1
   one           2
   three         1
b  four          1
   one           1
   three         3
   two           3
c  one           1
   three         1
   two           3
d  four          1
   one           1
   two           1